apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "roset-csi.fullname" . }}-node
  labels:
    {{- include "roset-csi.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "roset-csi.name" . }}-node
      {{- include "roset-csi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "roset-csi.name" . }}-node
        {{- include "roset-csi.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "roset-csi.serviceAccountName" . }}
      hostNetwork: true
      containers:
        - name: roset-csi-driver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--endpoint=unix:///csi/csi.sock"
            - "--node-id=$(NODE_ID)"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet
              mountPropagation: Bidirectional
            - name: device-dir
              mountPath: /dev
            - name: secrets-dir
              mountPath: /var/run/secrets/roset
        
        - name: csi-node-driver-registrar
          image: {{ .Values.sidecars.registrar.image | quote }}
          args:
            - "--csi-address=/csi/csi.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/roset-csi/csi.sock"
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration

      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/roset-csi
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
            type: Directory
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
        - name: secrets-dir
          hostPath:
            path: /var/run/secrets/roset
            type: DirectoryOrCreate
